header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors
    copyright-year: '2022'

  paths:
    - '**/*.go'
    - '**/*.s'

  paths-ignore:
    - '**/autocertcache.go'
  comment: on-failure
